name: event_frontend
description: A Flutter web app for managing and registering to events.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State management
  provider: ^6.1.2

  # HTTP client for API calls
  dio: ^5.7.0

  # Material icons
  flutter_svg: ^2.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
